#!/bin/bash
# Copyright © 2020 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

shopt -s nullglob

basedir=/run/media/mu/NO_NAME

for dir in $basedir/DCIM/*/; do
    if ! compgen -G "$dir"'*.JPG' > /dev/null; then
        continue
    fi
    rename-with-datetime --prefix Virb "$dir"*.JPG
    mv "$dir"*.jpg "$HOME/TODO/"
done

mv $basedir/Garmin/GPX/*.gpx "$HOME/Dokumente/Verkehr/Heatmap"
